add lavarel actions

diff --git a/.github/workflows/build_test_release_laravel.yml b/.github/workflows/build_test_release_laravel.yml
--- a/.github/workflows/build_test_release_laravel.yml
+++ b/.github/workflows/build_test_release_laravel.yml
@@ -13,7 +13,7 @@ jobs:
       DB_DATABASE: pims
       DB_PORT: 3306
       DB_USER: root
-      DB_PASSWORD: secret
+      DB_PASSWORD: root
 
     strategy:
       matrix:
@@ -104,7 +104,15 @@ jobs:
 
       # Unit Test
       - name: Execute tests (Unit and Feature tests) via PHPUnit
-        run: vendor/bin/phpunit --testdox
+        run: vendor/bin/phpunit --log-junit reports/test_result.xml
+
+      - name: Test Report
+        uses: dorny/test-reporter@v1
+        if: success() || failure()    # run this step even if previous step failed
+        with:
+          name: JEST Tests            # Name of the check run which will be created
+          path: reports/test*.xml    # Path to test results
+          reporter: jest-junit        # Format of test results
 
       # Code quality
 #      - name: Execute Code Sniffer via phpcs
